defaults:
  - dataset: cifar10

result_path: /result/

model: resnet18
seed: 0
lr: 3e-4
batch_size: 128
num_workers: 4
device: 'cuda:0'
num_epochs: 400
is_pretrained: False

proportion_metric: ce
mini_batch: 4
num_instances: 2048
val_metric: l1

consistency: none